
import React, { useState } from 'react';
import { Sparkles, FileText, Beaker, Copy, Check, Download, BookOpen, FileCode } from 'lucide-react';
import { generateContent } from '../services/generator';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { jsPDF } from 'jspdf';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

const ContentFactory = () => {
    const [activeTab, setActiveTab] = useState('theory');
    const [topic, setTopic] = useState('');
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);

    const handleGenerate = async () => {
        if (!topic.trim()) return;

        setLoading(true);
        setResult(null);

        try {
            if (activeTab === 'wiki') {
                // Wikipedia API Call
                const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(topic)}`);
                if (!response.ok) throw new Error('Wiki article not found');
                const data = await response.json();

                setResult({
                    type: 'wiki',
                    title: data.title,
                    content: data.extract,
                    thumbnail: data.thumbnail?.source,
                    url: data.content_urls?.desktop?.page
                });
            } else {
                // Existing AI Generation
                const response = await generateContent(topic, activeTab);
                setResult(response.data);
            }
        } catch (error) {
            console.error("Failed to generate", error);
            setResult({ error: "Could not fetch content. Please try a different topic." });
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = () => {
        const text = result?.content || '';
        if (text) {
            navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const handleDownloadPDF = () => {
        if (!result) return;

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        const maxLineWidth = pageWidth - (margin * 2);

        // Header
        doc.setFontSize(22);
        doc.setTextColor(40, 44, 52);
        doc.text(result.title || topic, margin, margin + 10);

        // Content / Body
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);

        const splitText = doc.splitTextToSize(result.content || '', maxLineWidth);
        doc.text(splitText, margin, margin + 30);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by Learning Platform | Source: ${activeTab === 'wiki' ? 'Wikipedia' : 'AI Analysis'}`, margin, doc.internal.pageSize.getHeight() - 10);

        doc.save(`${(result.title || topic).replace(/\s+/g, '_')}.pdf`);
    };

    const handleDownloadTex = () => {
        if (!result) return;

        const content = result.content || '';
        const title = result.title || topic;

        // Basic LaTeX Template
        const texTemplate = `\\documentclass{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{graphicx}
\\usepackage{hyperref}

\\title{${title}}
\\author{Learning Platform AI}
\\date{\\today}

\\begin{document}

\\maketitle

\\section*{Overview}
${content}

\\end{document}
`;

        const blob = new Blob([texTemplate], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/\s+/g, '_')}.tex`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="page-container">
            <h1 className="gradient-text" style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>Content Factory</h1>
            <p style={{ color: 'var(--text-muted)', marginBottom: '3rem', fontSize: '1.1rem' }}>
                Generate or fetch grounded learning materials.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: 'minmax(350px, 1fr) 1.5fr', gap: '2rem', alignItems: 'start' }}>

                {/* Input Section */}
                <div className="glass-panel" style={{ padding: '2rem', borderRadius: 'var(--radius-lg)' }}>
                    <div style={{ marginBottom: '2rem' }}>
                        <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500' }}>Source Mode</label>
                        <div style={{ display: 'flex', gap: '0.5rem', background: 'rgba(0,0,0,0.05)', padding: '0.25rem', borderRadius: 'var(--radius-md)' }}>
                            {[
                                { id: 'theory', icon: FileText, label: 'AI Theory' },
                                { id: 'lab', icon: Beaker, label: 'AI Lab' },
                                { id: 'wiki', icon: BookOpen, label: 'Wikipedia' }
                            ].map(tab => (
                                <button
                                    key={tab.id}
                                    onClick={() => setActiveTab(tab.id)}
                                    style={{
                                        flex: 1,
                                        padding: '0.75rem 0.5rem',
                                        borderRadius: 'var(--radius-sm)',
                                        background: activeTab === tab.id ? 'var(--accent-primary)' : 'transparent',
                                        color: activeTab === tab.id ? 'white' : 'var(--text-secondary)',
                                        fontWeight: '500',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        gap: '0.5rem',
                                        fontSize: '0.9rem',
                                        transition: 'all 0.3s',
                                        border: 'none',
                                        cursor: 'pointer'
                                    }}
                                >
                                    <tab.icon size={16} />
                                    {tab.label}
                                </button>
                            ))}
                        </div>
                    </div>

                    <div style={{ marginBottom: '2rem' }}>
                        <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500' }}>Topic / Query</label>
                        <textarea
                            value={topic}
                            onChange={(e) => setTopic(e.target.value)}
                            placeholder={activeTab === 'wiki' ? "Enter a Wikipedia article title (e.g. 'Quantum Mechanics')..." : "Describe what you want to learn..."}
                            style={{
                                width: '100%',
                                height: '150px',
                                padding: '1rem',
                                borderRadius: 'var(--radius-md)',
                                border: '1px solid var(--border-color)',
                                background: 'rgba(30, 41, 59, 0.7)', // Dark semi-transparent
                                color: '#e2e8f0', // Light Text
                                fontSize: '1rem',
                                outline: 'none',
                                resize: 'none'
                            }}
                        />
                    </div>

                    <button
                        className="btn-primary"
                        onClick={handleGenerate}
                        disabled={loading || !topic.trim()}
                        style={{
                            width: '100%',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: '0.5rem',
                            padding: '1rem',
                            opacity: (loading || !topic.trim()) ? 0.7 : 1,
                            cursor: (loading || !topic.trim()) ? 'not-allowed' : 'pointer'
                        }}
                    >
                        <Sparkles size={20} className={loading ? 'spinning' : ''} />
                        <span>{loading ? 'Processing...' : activeTab === 'wiki' ? 'Fetch Article' : 'Generate Content'}</span>
                    </button>
                </div>

                {/* Output Preview */}
                <div className="glass-panel" style={{
                    padding: '2rem',
                    borderRadius: 'var(--radius-lg)',
                    minHeight: '500px',
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative'
                }}>
                    {result && !result.error ? (
                        <>
                            <div style={{
                                display: 'flex',
                                justifyContent: 'space-between',
                                alignItems: 'center',
                                marginBottom: '1.5rem',
                                borderBottom: '1px solid var(--border-color)',
                                paddingBottom: '1rem'
                            }}>
                                <h3 style={{ margin: 0, fontSize: '1.25rem' }}>
                                    {result.title || 'Generated Result'}
                                </h3>
                                <div style={{ display: 'flex', gap: '0.5rem' }}>
                                    <button
                                        onClick={handleCopy}
                                        title="Copy text"
                                        style={{
                                            background: 'transparent',
                                            border: '1px solid var(--border-color)',
                                            padding: '0.5rem',
                                            borderRadius: 'var(--radius-md)',
                                            cursor: 'pointer',
                                            color: 'var(--text-secondary)'
                                        }}
                                    >
                                        {copied ? <Check size={18} color="green" /> : <Copy size={18} />}
                                    </button>
                                </div>
                            </div>

                            <div className="markdown-content" style={{ lineHeight: '1.6', overflowY: 'auto', flex: 1, marginBottom: '2rem' }}>
                                {activeTab === 'wiki' && result.thumbnail && (
                                    <img
                                        src={result.thumbnail}
                                        alt={result.title}
                                        style={{ float: 'right', marginLeft: '1rem', marginBottom: '1rem', borderRadius: 'var(--radius-md)', maxWidth: '200px' }}
                                    />
                                )}

                                <ReactMarkdown
                                    remarkPlugins={[remarkMath]}
                                    rehypePlugins={[rehypeKatex]}
                                    components={{
                                        code({ node, inline, className, children, ...props }) {
                                            const match = /language-(\w+)/.exec(className || '')
                                            return !inline && match ? (
                                                <SyntaxHighlighter
                                                    style={vscDarkPlus}
                                                    language={match[1]}
                                                    PreTag="div"
                                                    {...props}
                                                >
                                                    {String(children).replace(/\n$/, '')}
                                                </SyntaxHighlighter>
                                            ) : (
                                                <code className={className} {...props} style={{ background: '#eee', padding: '2px 4px', borderRadius: '4px' }}>
                                                    {children}
                                                </code>
                                            )
                                        }
                                    }}
                                >
                                    {result.content}
                                </ReactMarkdown>
                            </div>

                            {/* Download Section at Bottom */}
                            <div style={{
                                marginTop: 'auto',
                                paddingTop: '1.5rem',
                                borderTop: '1px solid var(--border-color)',
                                display: 'flex',
                                justifyContent: 'flex-end',
                                gap: '1rem'
                            }}>
                                <button
                                    onClick={handleDownloadTex}
                                    style={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '0.75rem',
                                        background: 'transparent',
                                        border: '1px solid var(--text-muted)',
                                        color: 'var(--text-primary)',
                                        padding: '0.75rem 1.5rem',
                                        borderRadius: 'var(--radius-md)',
                                        cursor: 'pointer',
                                        fontWeight: '500',
                                        transition: 'transform 0.2s',
                                    }}
                                    onMouseOver={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
                                    onMouseOut={(e) => e.currentTarget.style.transform = 'translateY(0)'}
                                >
                                    <FileCode size={18} />
                                    Download .tex
                                </button>
                                <button
                                    onClick={handleDownloadPDF}
                                    style={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '0.75rem',
                                        background: 'var(--accent-primary)', // Accent Color
                                        color: 'white',
                                        padding: '0.75rem 1.5rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: 'none',
                                        cursor: 'pointer',
                                        fontWeight: '500',
                                        transition: 'transform 0.2s',
                                        boxShadow: '0 4px 6px rgba(0,0,0,0.1)'
                                    }}
                                    onMouseOver={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
                                    onMouseOut={(e) => e.currentTarget.style.transform = 'translateY(0)'}
                                >
                                    <Download size={18} />
                                    Download {activeTab === 'wiki' ? 'Article' : 'Guide'} as PDF
                                </button>
                            </div>
                        </>
                    ) : (
                        <div style={{
                            flex: 1,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            flexDirection: 'column',
                            color: 'var(--text-muted)'
                        }}>
                            {loading ? (
                                <Sparkles size={48} className="spinning" style={{ marginBottom: '1rem', color: 'var(--accent-primary)' }} />
                            ) : (
                                <BookOpen size={48} style={{ opacity: 0.2, marginBottom: '1rem' }} />
                            )}
                            <p>{loading ? 'Processing...' : result?.error || 'Select a mode and enter a topic to start'}</p>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
};

export default ContentFactory;
